name: Function apps deploy

on:
  push:
    tags:
    - 'v*'

env:
  SMS_PUBLISH_PATH: src/NhnToast.Sms/bin/Release/net6.0/publish/
  SMS_VERIFICATION_PUBLISH_PATH: src/NhnToast.Sms.Verification/bin/Release/net6.0/publish/
  SMS_PUBLISH_NAME: SmsApp
  SMS_VERIFICATION_PUBLISH_NAME: SmsVerificationApp

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore .

    - name: Build solution
      shell: bash
      run: |
        dotnet build . -c Release

    - name: Test solution
      shell: bash
      run: |
        dotnet test . -c Release

    - name: Create FunctionApp artifact
      shell: bash
      run: |
        dotnet publish -c Release
    
    - name: Upload SMS app artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.SMS_PUBLISH_NAME }}
        path: ${{ github.workspace }}/${{ env.SMS_PUBLISH_PATH }}
        retention-days: 7
        
    - name: Upload SMS Verification artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.SMS_VERIFICATION_PUBLISH_NAME }}
        path: ${{ github.workspace }}/${{ env.SMS_VERIFICATION_PUBLISH_PATH }}
        retention-days: 7

  Continuous-Deployment:
    runs-on: ubuntu-latest
    needs: Continuous-Integration

    steps:
    - name: Download FunctionApp artifacts
      uses: actions/download-artifact@v3

    - name: Zip FunctionApp artifacts
      run: |
          cd ${{env.SMS_PUBLISH_NAME}}
          zip ${{env.SMS_PUBLISH_NAME}}.zip ./* -r
          cd ${{ github.workspace }}

          cd ${{env.SMS_VERIFICATION_PUBLISH_NAME}}
          zip ${{env.SMS_VERIFICATION_PUBLISH_NAME}}.zip ./* -r
          cd ${{ github.workspace }}

          mkdir published
          mv ${{env.SMS_PUBLISH_NAME}}/${{env.SMS_PUBLISH_NAME}}.zip published/${{env.SMS_PUBLISH_NAME}}.zip
          mv ${{env.SMS_VERIFICATION_PUBLISH_NAME}}/${{env.SMS_VERIFICATION_PUBLISH_NAME}}.zip published/${{env.SMS_VERIFICATION_PUBLISH_NAME}}.zip

    - name: Release FunctionApp artifacts to GitHub
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        name: Release ${{ github.ref }}
        body_path: release-notes/${{ github.ref }}.md
        generate_release_notes: true
        files: |
          published/${{env.SMS_PUBLISH_NAME}}.zip
          published/${{env.SMS_VERIFICATION_PUBLISH_NAME}}.zip
